version: '3.7'

services:
  database:
    image: postgres:14.2
    container_name: database
    restart: always
    ports:
      - '${PG_PORT:-5432}:${PG_PORT:-5432}'
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}

volumes:
  database_volume:
