version: '3.8'

services:
  database:
    image: postgres:14.2
    container_name: database
    restart: always
    ports:
      - '${PG_PORT:-5432}:${PG_PORT:-5432}'
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}
  app:
    container_name: app
    build:
      context: .
      target: dependencies
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - '${PORT:-3333}:${PORT:-3333}'
    depends_on:
      - database
    env_file:
      - .env
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  database_volume:
  node_modules:
